CW-432-Add-Bitcoin-Cash-BCH
cake-tech/cake_wallet pull request #1041
Opened 2023-08-13 16:21 UTC by Serhii-Borodenko

Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2023-09-18 14:30 UTC, SamsungGalaxyPlayer commented on lib/core/address_validator.dart
> +        return [42, 43, 44, 54, 55];
As I understand, this will permit these non-42 lengths for all the preceding ETH assets as well, is this desired?

2023-10-05 01:15 UTC, OmarHatem28 requested changes
Looks good and so far easy to review, thanks for that ^^

those are my comments till now, and please fix the conflicts with main, but please be careful while merging the conflicts as the changes are very close.
mostly you would accept both changes since we wanna keep Nano and add Bitcoin cash, yet be careful to avoid any unnecessary time to fix some merging issues

2023-10-06 12:48 UTC, Serhii-Borodenko commented on lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
> +    var base = address;
the CashAddr format already has the prefix 'bitcoincash:'

2023-10-06 12:48 UTC, Serhii-Borodenko commented on cw_bitcoin/pubspec.yaml
> +      url: https://github.com/Serhii-Borodenko/cw_bitbox.git
done

2023-10-06 12:53 UTC, Serhii-Borodenko commented on cw_bitcoin_cash/lib/src/bitcoin_cash_balance.dart
> +  String get formattedAvailableBalance => balance.toString();
I removed bitcoin_cash_balance.dart since we're not using it. Now I'm just using bitcoinAmountToString(amount: balance) instead.

2023-10-09 09:36 UTC, Serhii-Borodenko commented on lib/view_model/unspent_coins/unspent_coins_details_view_model.dart
> +import 'package:cw_bitcoin/electrum_wallet_addresses.dart';
fixed

2023-10-09 09:36 UTC, Serhii-Borodenko commented on lib/view_model/exchange/exchange_view_model.dart
> +        break;
fixed

2023-10-09 09:36 UTC, Serhii-Borodenko commented on lib/view_model/exchange/exchange_view_model.dart
> +            bitcoinCash!.getBitcoinCashTransactionPrioritySlow();
done

2023-10-09 09:36 UTC, Serhii-Borodenko commented on lib/src/screens/unspent_coins/unspent_coins_list_page.dart
> +import 'package:cw_bitcoin/electrum_wallet_addresses.dart';
done

2023-10-09 09:36 UTC, Serhii-Borodenko commented on lib/bitcoin/cw_bitcoin.dart
> +				bitcoinUnspent.bitcoinAddressRecord,
yes, it works

2023-10-09 09:36 UTC, Serhii-Borodenko commented on cw_bitcoin/lib/bitcoin_address_record.dart
> +  String address;
Tried different approach for Address record. Returned it back

2023-10-11 13:18 UTC, OmarHatem28 requested changes

2023-10-12 09:53 UTC, Serhii-Borodenko commented on lib/view_model/exchange/exchange_view_model.dart
> +            ethereum!.getDefaultTransactionPriority();
fixed

2023-10-12 09:53 UTC, Serhii-Borodenko commented on cw_bitcoin/lib/electrum_wallet.dart
> +import 'package:bitcoin_flutter/bitcoin_flutter.dart';
fixed

2023-10-12 22:49 UTC, OmarHatem28 approved these changes

2023-10-12 22:50 UTC, merged