CW-472-QR-code-restore-If-a-user-scans-a-wallet-seed-that-does-NOT-include
cake-tech/cake_wallet pull request #1081
Opened 2023-09-08 17:42 UTC by Serhii-Borodenko

Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2023-10-13 02:00 UTC, OmarHatem28 requested changes
Overall good, but the code can be slightly enhanced.

please, solve the conflicts with main and fix the comments, and make any enhancements that you see fit

2023-10-18 09:46 UTC, Serhii-Borodenko commented on lib/view_model/restore/wallet_restore_from_qr_code.dart
> +    List<int> patternCounts = walletType == WalletType.monero ? [25, 14, 13] : [24, 18, 12];
I'm not totally sure, but I think I found it [here](https://www.getmonero.org/resources/user-guides/restore_account.html#:~:text=this%20guide.-,What%20is%20needed%20to%20restore%20a%20wallet%20from%20mnemonic%20seed%3F,date%20of%20your%20wallet%2C%20since%20it%20makes%20your%20wallet%20synchronization%20faster.,-Where%20can%20I).

2023-10-18 11:12 UTC, Serhii-Borodenko commented on lib/view_model/restore/wallet_restore_from_qr_code.dart
> +    'ethereum-wallet': WalletType.ethereum,
bch and nano added

2023-10-24 23:37 UTC, OmarHatem28 approved these changes

2023-10-25 00:20 UTC, merged