Cw 473 exchange refactoring
cake-tech/cake_wallet pull request #1126
Opened 2023-10-13 10:49 UTC by konstantinullrich

# Description

Refactor parts of the exchange code, to be simpler. Remove deprecated Exchanges like MorphToken and XMR.to

# Pull Request - Checklist  

- [x] Initial Manual Tests Passed
- [x] Double check modified code and verify it with the feature/task requirements
- [x] Format code
- [x] Look for code duplication
- [x] Clear naming for variables and methods

2023-10-17 01:21 UTC, OmarHatem28 requested changes

2023-10-17 07:46 UTC, konstantinullrich commented on lib/exchange/provider/changenow_exchange_provider.dart
> +    CryptoCurrency.zaddr,
`zaddr` refers to Shielded Zcash which is rarely supported. There is no official documentation about the support of shielded Zcash addresses, but when I tried entering a valid shielded address it threw the error Invalid address. When I used an unshielded address the exchange worked.

2023-10-17 23:48 UTC, OmarHatem28 approved these changes
Looks good, thanks for refactoring what's needed.
Please solve the conflicts with main

2023-10-18 21:22 UTC, OmarHatem28 requested changes
I keep forgetting to tell you this, but please keep the brackets for the conditions (`if` and `else`) as they are more readable this way, even for a 1 line of code

2023-10-18 21:22 UTC, OmarHatem28 commented on lib/view_model/exchange/exchange_trade_view_model.dart
> +
you haven't added `TradeProviderUnsupportedItem` to the items in this class.

also, there is no need for this line anymore

2023-10-18 21:22 UTC, OmarHatem28 commented on lib/view_model/trade_details_view_model.dart
> +      _updateItems();
I believe this should be swapped with `_updateTrade()` on line 62

2023-10-18 21:22 UTC, OmarHatem28 commented on lib/view_model/trade_details_view_model.dart
> +    if (_provider == null) throw ExchangeProviderUnsupportedException(trade.provider);
and this can be removed by the change above, since we will be sure its not null

2023-10-25 12:27 UTC, OmarHatem28 approved these changes

2023-10-25 20:58 UTC, merged