feat: Implement NFT Tab for Eth
cake-tech/cake_wallet pull request #1166
Opened 2023-11-07 15:24 UTC by Blazebrain

…FTs linked to the wallet address

Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [x] Initial Manual Tests Passed
- [x] Double check modified code and verify it with the feature/task requirements
- [x] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2023-11-16 19:09 UTC, OmarHatem28 requested changes

2023-11-20 10:15 UTC, Blazebrain commented on lib/entities/wallet_nft_response.dart
Modified them to reflect this

2023-11-20 10:22 UTC, Blazebrain commented on lib/view_model/dashboard/nft_view_model.dart
> +        "normalizeMetadata": "true",
Added documentation to the code

2023-11-20 10:28 UTC, Blazebrain commented on lib/router.dart
> +          nftViewModel: getIt.get<NFTViewModel>(),
Adjusted it to receive the same instance of `NFTViewModel` as it's parent

2023-11-22 15:48 UTC, OmarHatem28 commented on lib/router.dart
please make sure you have the line width set to 100 in your IDE configuration as agreed on

2023-11-22 15:49 UTC, OmarHatem28 commented on lib/polygon/polygon.dart
unrelated to this branch and should be ignored in the polygon branch

2023-11-22 16:53 UTC, OmarHatem28 approved these changes

2023-11-22 17:43 UTC, merged