Wownero integration #2
cake-tech/cake_wallet pull request #1260
Opened 2024-01-05 13:45 UTC by sanderfoobar

Continuation of https://github.com/cake-tech/cake_wallet/pull/362

Wownero support. Uses Polyseed this time (we are phasing out `wownero-seed`).

I tested: sending/receiving/history on both Android (arm64) and Android emulator (x86_64).

![Screenshot from 2024-01-03 13-59-59](https://github.com/cake-tech/cake_wallet/assets/1478325/afc8f6b2-a216-4454-bad9-34dcce45f5c3)

## Notes:

There are still some to-do's:

### 1. Fiat <-> WOW calculations

Probably requires https://github.com/cake-tech/cake_wallet/issues/361

### 2. Accounts runtime error

`Dashboard -> Receive -> Accounts` gives an error. Fix would be to leave out the accounts feature in its entirety just like last PR - as we do not use the account feature in Wownero. Would be nice if someone could exclude this feature when `coin type == wownero`.

### 3. Exchange button

The exchange button at the dashboard for WOW should (probably) not be active.

### 4. iOS/macos untested

Untested - getting the iOS emulator to run is a bit difficult with the certificates and all.

### 5. pubspec

I updated `watcher` to `1.1.0`.

### 6. Docker fixes

The following had some issues:

```text
cd scripts/docker
docker build --tag=build_monero_deps --progress plain --no-cache .
docker compose up
```

I fixed various things in `scripts/docker`:

- Changed file permission mode
- `build_haven.sh` interpreter changed to `/bin/bash`
- Added build requirement `byacc` to `apt get` in `Dockerfile`, it is needed for libunbound to compile correctly
- Changed carriage return to Unix style (sorry for the diffs)

### 7. Wownero branch

Changes to Wownero to facilitate Cake using wow's wallet2 API went into a branch called [cake-fixes](https://git.wownero.com/wownero/wownero/commits/branch/cake-fixes). The build script `build_wownero.sh` is pinned to a commit hash.

### 8. Polyseed

Waiting on:

- https://github.com/tevador/polyseed/pull/10
- https://github.com/cake-tech/polyseed_dart/pull/1

Current situation is that create wallet generates a Polyseed with the Monero coin type.

2024-01-25 03:01 UTC, nahuhh reviewed
Just spotted a couple places that were 12 instead of 11

2024-01-25 03:11 UTC, nahuhh commented on cw_core/lib/node.dart
>            return requestElectrumServer();
```suggestion
         case WalletType.monero:
         case WalletType.wownero:
         case WalletType.haven:
           return requestMoneroNode();
         case WalletType.bitcoin:
           return requestElectrumServer();
```

perhaps ^ + del L145-L146 

(missing a space / tab is misaligned for the wownero case line)

2024-01-25 03:14 UTC, nahuhh commented
>3. Exchange button
>
>The exchange button at the dashboard for WOW should (probably) not be active.

trocador supports wownero iirc. So i think it can stay (would need to add wownero to the list of swappable coins)

2024-01-26 18:03 UTC, nahuhh commented
@OmarHatem28  please look into

> ### 1. Fiat <-> WOW calculations
> 
> Probably requires https://github.com/cake-tech/cake_wallet/issues/361

>### 2. Accounts runtime error
> 
> `Dashboard -> Receive -> Accounts` gives an error. Fix would be to leave out the accounts feature in its entirety just like last PR - as we do not use the account feature in Wownero. Would be nice if someone could exclude this feature when `coin type == wownero`.
> 
> ### 3. Exchange button
> 
> ~~The exchange button at the dashboard for WOW should (probably) not be active.~~

Trocador supports wownero, so you should be able to add wow as a supported currency
> 
> ### 4. iOS/macos untested
> 
> Untested - getting the iOS emulator to run is a bit difficult with the certificates and all.

> ### 8. Polyseed
> 
> Waiting on:
> 
> - https://github.com/cake-tech/polyseed_dart/pull/1


Needs review / confirm everything ok:
> ### 5. pubspec
> 
> I updated `watcher` to `1.1.0`.
> 
> ### 6. Docker fixes
> 
> The following had some issues:
> 
> ```text
> cd scripts/docker
> docker build --tag=build_monero_deps --progress plain --no-cache .
> docker compose up
> ```
> 
> I fixed various things in `scripts/docker`:
> 
> - Changed file permission mode
> - `build_haven.sh` interpreter changed to `/bin/bash`
> - Added build requirement `byacc` to `apt get` in `Dockerfile`, it is needed for libunbound to compile correctly
> - Changed carriage return to Unix style (sorry for the diffs)
> 
> ### 7. Wownero branch
> 
> Changes to Wownero to facilitate Cake using wow's wallet2 API went into a branch called [cake-fixes](https://git.wownero.com/wownero/wownero/commits/branch/cake-fixes). The build script `build_wownero.sh` is pinned to a commit hash.
> 



> Current situation is that create wallet generates a Polyseed with the Monero coin type.

need to change to wownero after polyseed_dart pr merge

2024-01-26 18:15 UTC, nahuhh requested changes

2024-01-26 18:15 UTC, nahuhh commented on assets/wownero_node_list.yml
> +  useSSL: false
```suggestion
  uri: node3.monerodevs.org:34568
  is_default: true
  useSSL: false
-
  uri: node2.monerodevs.org:34568
  is_default: false
  useSSL: false
-
  uri: node.monerodevs.org:34568
  is_default: false
  useSSL: false
```

2024-01-26 18:40 UTC, OmarHatem28 commented
Hi @nahuhh thanks for helping in reviewing this PR

I am currently in the review process but I might submit my current comments so far until I complete the review.

I will review the Polyseed PR afterwards but @sanderfoobar can't we make both seed types (normal, polyseed) supported?

Also, like @nahuhh suggested, can you please remove the Accounts feature and all its related files, and update the PR with the latest main to resolve the conflicts

2024-01-26 18:40 UTC, OmarHatem28 requested changes
No need for `android/app/src/main/java/com/cakewallet/wownero/` since there won't be a separate app for wownero and it would be included in Cake Wallet

2024-01-26 18:47 UTC, nahuhh commented on lib/src/screens/seed/pre_seed_page.dart
> +        return 16;  // always polyseed
currently using monero's polyseed (so likely creates invalid seeds)

2024-03-04 18:44 UTC, OmarHatem28 commented
Hi @sanderfoobar We're excited about the changes you've proposed and adding Wownero, and we would love to see this PR integrated into the Cake.
If you have any questions or need further assistance with your pull request, please don't hesitate to let me know.

2024-03-15 20:44 UTC, nahuhh commented
@OmarHatem28 to proceed and properly test, from cake side, we need https://github.com/cake-tech/polyseed_dart/pull/1

2024-03-15 23:15 UTC, OmarHatem28 commented
@nahuhh merged

2024-03-17 05:41 UTC, nahuhh requested changes

2024-03-17 05:41 UTC, nahuhh commented on cw_core/lib/crypto_currency.dart
> +  static const wow = CryptoCurrency(title: 'WOW', fullName: 'Wownero', raw: 89, name: 'wow', iconPath: 'assets/images/wownero_icon.png', decimals: 11);
```suggestion
  static const wow = CryptoCurrency(title: 'WOW', fullName: 'Wownero', raw: 92, name: 'wow', iconPath: 'assets/images/wownero_icon.png', decimals: 11);
```

2024-03-17 05:41 UTC, nahuhh commented on cw_wownero/ios/Classes/wownero_api.cpp
> +    m_account->refresh();
@OmarHatem28 
idk where to remove accounts. Can you guys handle

1. Removing accounts
2. Adding to fiat api
3. Adding to exchange

2024-03-17 05:54 UTC, nahuhh approved these changes
soon, no more tm

2024-03-17 05:59 UTC, nahuhh commented
need from cake for release:
- [ ] ios test
- [ ] fiat api 
- [ ] exchange integration
- [ ] wownero easter eggs (jk.)

2024-03-21 23:59 UTC, nahuhh commented
Pinging @OmarHatem28

2024-03-31 17:27 UTC, MrCyjaneK commented
Hey! There is a little detail that I've encountered when a combination of wownero and monero is used together in one process as a shared library.

The issue is as follows
- once you open wownero wallet it works great
- when you try to use monero wallet it uses previously loaded wownero symbols
- so when you opened one of the coins, another one may reuse it's symbols.

I've encountered this issue on linux while working on another wallet that uses cw libraries, I'm not sure if this is the case with cake in this PR (I'll check it once I have some more time), but this is something that may cause issue.

2024-04-01 13:05 UTC, OmarHatem28 commented
@MrCyjaneK thanks for sharing this issue, we will check if it's indeed the case in #1345, alongside the other fixes, feel free to try the APK in there and share your insights on the PR if you find anything missing or should be fixed or needs enhancements.
we will try to give more attention to finalizing Wownero soon if everything goes smooth

2024-04-01 14:02 UTC, MrCyjaneK commented
@sanderfoobar up to my current knowledge it is.

2024-07-02 20:00 UTC, OmarHatem28 commented
Hey, thanks for all the contributions so far, Wownero is now in Beta with this PR #1485 
please feel free to try it out, and send us your feedback.
will be closing this in favor of #1485

2024-07-02 20:00 UTC, closed without merging