Remove moonpay secret use exchange-helper instead
cake-tech/cake_wallet pull request #1343
Opened 2024-03-21 16:32 UTC by konstantinullrich

# Description

Use Exchange-helper to remove Moonpay secret

# Pull Request - Checklist  

- [x] Initial Manual Tests Passed
- [x] Double check modified code and verify it with the feature/task requirements
- [x] Format code
- [x] Look for code duplication
- [x] Clear naming for variables and methods

2024-03-21 18:52 UTC, SamsungGalaxyPlayer commented on lib/buy/moonpay/moonpay_provider.dart
> +        throw Exception("WalletType is not available for Robinhood ${wallet.type}");
moonpay?

2024-03-21 23:02 UTC, konstantinullrich commented on lib/buy/moonpay/moonpay_provider.dart
> +        throw Exception("WalletType is not available for Robinhood ${wallet.type}");
```suggestion
        throw Exception("WalletType is not available for Moonpay ${wallet.type}");
```

2024-03-25 12:15 UTC, OmarHatem28 requested changes

2024-03-25 12:15 UTC, OmarHatem28 commented on lib/buy/moonpay/moonpay_provider.dart
> +        throw Exception("WalletType is not available for Moonpay ${wallet.type}");
what about the rest?

2024-03-25 18:16 UTC, OmarHatem28 approved these changes

2024-03-25 18:16 UTC, merged