Cw 602 nano bad rep
cake-tech/cake_wallet pull request #1356
Opened 2024-04-01 20:59 UTC by fossephate

Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2024-04-10 00:03 UTC, OmarHatem28 requested changes

2024-04-10 00:03 UTC, OmarHatem28 commented on lib/src/screens/nodes/widgets/node_form.dart
> +                  validator: NodePathValidator(),
wouldn't this make it required?
while it can be empty

2024-04-10 15:36 UTC, fossephate commented on cw_nano/lib/nano_client.dart
> +      return 100;
defaulting to a score of 100 ensures that we don't accidentally show the rep warning if the api goes down or something goes wrong
We want to warn users to change their rep when possible, but it isn't so urgent that we should risk a false positive

2024-04-10 15:46 UTC, fossephate commented on assets/nano_node_list.yml
I got them from this list:
https://publicnodes.somenano.com
they're just community nodes so the uptime on them isn't guaranteed or anything but I just wanted to give users more options

2024-04-10 22:14 UTC, fossephate commented on lib/src/screens/nano/nano_change_rep_page.dart
> +import 'package:cw_nano/n2_node.dart';
should I just move the class? if so, where?
it's not a function like in past cases so I'm not sure how it'd fit into the usual solution of putting a function in cw_nano.dart

2024-04-12 12:36 UTC, OmarHatem28 approved these changes

2024-04-12 12:36 UTC, merged