feat: Add warning before adding erc20 token via contract address
cake-tech/cake_wallet pull request #1663
Opened 2024-09-03 11:22 UTC by Blazebrain

Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2024-09-05 00:52 UTC, OmarHatem28 requested changes

2024-09-05 14:24 UTC, Blazebrain commented on lib/src/screens/dashboard/edit_token_page.dart
> +                        final hasPotentialError = await widget.homeSettingsViewModel
Alrighty

2024-09-07 14:39 UTC, OmarHatem28 approved these changes

2024-09-07 14:39 UTC, OmarHatem28 commented on .github/workflows/pr_test_build_linux.yml
> +          echo "const etherScanApiKey = '${{ secrets.ETHER_SCAN_API_KEY }}';" >> cw_evm/lib/.secrets.g.dart
```suggestion
          echo "const etherScanApiKey = '${{ secrets.ETHER_SCAN_API_KEY }}';" >> lib/.secrets.g.dart
```

2024-09-11 19:15 UTC, OmarHatem28 approved these changes

2024-09-11 21:19 UTC, merged