CW-782: Show error report popup without cooldown
cake-tech/cake_wallet pull request #1739
Opened 2024-10-09 13:14 UTC by MrCyjaneK

# Description

improve exception throwing on broken wallets
- put _lastOpenedWallet to avoid issues on windows (file is currently open by)
- don't throw corruptedWalletsSeed - instead store it inside of secureStorage
- await ExceptionHandler.onError calls where possible to makse sure that popup won't be canceled by some UI element
- adjust BaseAlertDialog to be scrollable if the text is too long
- add ExceptionHandler.resetLastPopupDate - that can be called when we want to show error report screen (bypassing cooldown)
# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2024-10-17 02:50 UTC, OmarHatem28 requested changes

2024-10-17 02:50 UTC, OmarHatem28 commented on lib/utils/exception_handler.dart
> +    await _saveException(
we don't want to await saving the exception, we can still show the user the popup until it gets saved

2024-10-17 02:50 UTC, OmarHatem28 commented on lib/utils/exception_handler.dart
> +            alertContent: content+"\n"+(seeds??""),
here I believe it would be duplicated, as the content is the error message, which contains the seeds as well

2024-10-17 02:50 UTC, OmarHatem28 commented on lib/src/screens/wallet_list/wallet_list_page.dart
> +          await ExceptionHandler.onError(FlutterErrorDetails(exception: err));
same,
same

2024-10-17 02:50 UTC, OmarHatem28 commented on lib/di.dart
haven't reviewed this file yet, but double check it as well please

2024-10-17 07:52 UTC, MrCyjaneK commented on lib/core/wallet_loading_service.dart
> +      secureStorageShared.write(key: "corruptedWalletsSeed", value: corruptedWalletsSeeds);
Otherwise the error report may contain the seed - which wouldn't be ideal

2024-11-11 10:26 UTC, OmarHatem28 commented on lib/core/wallet_loading_service.dart
> +      secureStorageShared.write(key: "corruptedWalletsSeed", value: corruptedWalletsSeeds);
Well we already ignore the error and don't save it, if the error string contains "corrupted seeds"

2024-11-28 19:28 UTC, merged

2024-12-02 04:43 UTC, xximwon reviewed
G