transaction description key id address
cake-tech/cake_wallet pull request #1755
Opened 2024-10-16 15:03 UTC by Serhii-Borodenko

Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2024-10-16 18:38 UTC, OmarHatem28 requested changes
in case of Monero this would fail, so you can either add a getter to Monero to get the primary address and use that like we do in Electrum, or if you have another idea in mind

2024-10-16 18:38 UTC, OmarHatem28 commented on lib/view_model/send/send_view_model.dart
> +          : wallet.walletAddresses.address;
this will be different for Monero each time

2024-10-16 18:38 UTC, OmarHatem28 commented on lib/view_model/transaction_details_view_model.dart
> +        : wallet.walletAddresses.address;
same

2024-10-17 14:05 UTC, Serhii-Borodenko commented
I think it would be better to add a primary address for all wallets

2024-10-18 02:54 UTC, OmarHatem28 approved these changes

2024-10-18 02:58 UTC, OmarHatem28 commented
> I think it would be better to add a primary address for all wallets

could have been better to set it from the parent `wallet_address.dart` like this
```
String get primaryAddress => address;
```
since it will be like this for all of the wallets, without having to modify each wallet file, and you would only need to override it in the needed wallets, but anyway that's minor, just thought I would let you know about it for future instances

2024-10-18 02:58 UTC, merged