Zano
cake-tech/cake_wallet pull request #1793
Opened 2024-11-06 14:23 UTC by MrCyjaneK

# Description

Early WIP, do not review. yet.

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2025-01-16 01:15 UTC, OmarHatem28 requested changes

2025-01-16 01:15 UTC, OmarHatem28 commented on cw_zano/lib/zano_wallet.dart
> +      throw ZanoWalletException("there's no zano asset with id $assetId");
let's make sure that those exceptions are caught and handled gracefully instead of showing the report error popup

2025-01-16 01:15 UTC, OmarHatem28 commented on cw_zano/lib/zano_wallet.dart
> +      }
```suggestion
      if (transactions.length == transactionHistory.transactions.length) {
        _isTransactionUpdating = false;
        return;
      }
```

2025-01-16 01:15 UTC, OmarHatem28 commented on cw_zano/lib/zano_wallet.dart
> +        GetWalletStatusResult walletStatus;
isn't this, too intensive to be done every 2 seconds?

2025-01-17 09:02 UTC, MrCyjaneK commented on cw_zano/lib/zano_wallet.dart
> +        GetWalletStatusResult walletStatus;
It should be fine, I didn't encounder any lags, and it's async anyway

2025-01-17 09:06 UTC, MrCyjaneK commented on cw_zano/lib/zano_wallet.dart
> +      throw ZanoWalletException("there's no zano asset with id $assetId");
added error handling in edit_token_page.dart

2025-01-17 09:28 UTC, MrCyjaneK commented on lib/view_model/wallet_restore_view_model.dart
> +            language: 'English');
API supports restoring from keys, we just don't show that in UI.

2025-01-17 09:28 UTC, MrCyjaneK commented on windows/CMakeLists.txt
> +#  COMPONENT Runtime)
It is now linked statically

2025-01-17 09:29 UTC, MrCyjaneK commented on scripts/android/build_zano.sh
right

2025-01-17 15:54 UTC, OmarHatem28 commented on lib/view_model/dashboard/home_settings_view_model.dart
> +    _updateFiatPrices(token);
still duplicate, just move the if condition below the other if conditions and remove the duplicate update functions

2025-01-17 15:54 UTC, OmarHatem28 commented on lib/view_model/wallet_new_vm.dart
> +        return zano!.createZanoNewWalletCredentials(name: name);
shouldn't it take the password as well?

2025-01-17 15:54 UTC, OmarHatem28 commented on lib/view_model/wallet_restore_view_model.dart
> +            language: 'English');
why tho?
plus, I didn't see it implemented in the code anyway

2025-01-17 15:54 UTC, OmarHatem28 commented on lib/view_model/exchange/exchange_view_model.dart
> +        _settingsStore.priority[wallet.type] = monero!.getMoneroTransactionPriorityAutomatic();
ok no problem then

2025-01-17 15:54 UTC, OmarHatem28 commented on cw_zano/lib/model/zano_asset.dart
still not removed

2025-01-17 15:54 UTC, OmarHatem28 commented on scripts/android/build_zano.sh
ok let's remove them then!

2025-01-17 15:54 UTC, OmarHatem28 commented on windows/CMakeLists.txt
> -  COMPONENT Runtime)
why is this removed?

2025-01-19 08:54 UTC, MrCyjaneK commented on windows/CMakeLists.txt
> -  COMPONENT Runtime)
It is now linked statically, no need for a separate DLL

2025-01-19 08:59 UTC, MrCyjaneK commented on cw_core/lib/node.dart
> +  Future<bool> requestMoneroNode({String methodName = "get_info"}) async {
get_info for monero/wownero getinfo for zano

2025-01-19 09:00 UTC, MrCyjaneK commented on lib/view_model/wallet_restore_view_model.dart
> +            language: 'English');
removed

2025-01-21 12:29 UTC, merged