added files to step users through building cake on ios
cake-tech/cake_wallet pull request #213
Opened 2022-01-05 04:59 UTC by tannerdsilva

2022-01-06 10:23 UTC, mkyq commented
`Intel Mac` - it should works same on arm too. 
`- Android SDK 28
  - Android NDK 17c`
  I'm not sure that android sdk and ndk are required for iOS build :)

2022-01-06 10:59 UTC, mkyq commented
And please add that need to checkout v4.2.7 tag after git clone

2022-01-06 11:24 UTC, mkyq commented
I just updated main with a lot of changes. Now need to update the instruction: 
before `$ flutter packages pub run build_runner build --delete-conflicting-outputs` in root app directory need to do next:
- `cd cw_core/` + `$ flutter packages pub run build_runner build --delete-conflicting-outputs`
(then cd ..) 
- `cd cw_monero/` + `$ flutter packages pub run build_runner build --delete-conflicting-outputs`

Also now need to generate different info.plist file and icon for monero.com and cakewallet apps. For that need to:
(in root directory)
- `cd scriptips/ios`
- `./app_env <monero.com OR cakewallet>` based on what type of the app you want to build
- `./app_config.sh`
(back to root directory)

Steps above can be done before call `flutter run` command.

2022-01-20 06:10 UTC, tannerdsilva commented
@mkyq pushed updates

2022-01-24 14:39 UTC, mkyq requested changes

2022-01-24 14:39 UTC, mkyq commented on howto-build-ios.md
> +Intel Mac
This instruction should works well on Apple arm too.

2022-01-24 14:39 UTC, mkyq commented on howto-build-ios.md
> +Flutter 2 or above
Need Flutter 2.0.4

2022-01-24 14:39 UTC, mkyq commented on howto-build-ios.md
> +	- Android NDK 17c
Is unnecessary for iOS

2024-10-24 03:32 UTC, closed without merging