Cw 09 implement picker screen with ability to search
cake-tech/cake_wallet pull request #250
Opened 2022-01-25 14:57 UTC by Serhii-Borodenko

-Created a new selection screen
-Added a search bar with the ability to search by name and full name of currencies
-Added cryptocurrency icons
-Added Cancel button to cancel search action
- Updated all localization files

2022-01-26 15:51 UTC, mkyq commented
@Serhii-Borodenko please update your PR with last changes from `main` and resolve merge conflicts

2022-02-07 09:51 UTC, mkyq requested changes

2022-02-21 14:44 UTC, mkyq requested changes

2022-02-21 14:44 UTC, mkyq commented on lib/src/screens/exchange/widgets/currency_picker.dart
> +      .toList();
Put that in initState method

2022-03-09 12:11 UTC, mkyq commented
cc @Serhii-Borodenko

2022-03-24 09:41 UTC, mkyq requested changes

2022-03-24 09:41 UTC, mkyq commented on lib/src/screens/exchange/widgets/currency_picker.dart
> +          .toList();
Why is that getter ? It should be just a function.

2022-03-24 09:41 UTC, mkyq commented on lib/src/screens/exchange/widgets/currency_picker.dart
> +                            'ryptoCurrency.xmr = ${subPickerItemsList[index].original == CryptoCurrency.xmr}');
Remove prints

2022-03-24 09:41 UTC, mkyq commented
cc @Serhii-Borodenko

2022-03-24 11:35 UTC, Serhii-Borodenko commented
done

2022-03-31 14:16 UTC, merged