Cw 55 allow saving templateswith fiat amount
cake-tech/cake_wallet pull request #343
Opened 2022-04-19 08:25 UTC by Serhii-Borodenko

Added ability to save templates with fiat amount

2022-04-22 15:11 UTC, mkyq requested changes

2022-04-22 15:11 UTC, mkyq commented on lib/src/screens/send/send_page.dart
> +
What that code should do ?

2022-04-22 15:12 UTC, mkyq commented
cc @Serhii-Borodenko

2022-04-26 11:45 UTC, Serhii-Borodenko commented on lib/src/screens/send/send_page.dart
> +
Removed print statement

2022-04-28 17:27 UTC, Serhii-Borodenko commented on lib/src/screens/send/send_page.dart
> +
@mkyq

2022-05-03 10:44 UTC, mkyq approved these changes

2022-05-03 10:44 UTC, merged