fix haven transaction info
cake-tech/cake_wallet pull request #373
Opened 2022-06-03 12:14 UTC by Serhii-Borodenko

Fixed display of Haven transaction info

2022-06-06 11:00 UTC, mkyq requested changes

2022-06-06 11:00 UTC, mkyq commented on lib/haven/cw_haven.dart
>      	return asset;
Improve formatting here

2022-06-07 07:25 UTC, Serhii-Borodenko commented on lib/haven/cw_haven.dart
>      	return asset;
done

2022-06-13 09:31 UTC, mkyq approved these changes

2022-06-13 09:32 UTC, merged