Ionia manage card UI
cake-tech/cake_wallet pull request #374
Opened 2022-06-07 03:15 UTC by godilite

2022-06-13 14:00 UTC, mkyq requested changes

2022-06-13 14:00 UTC, mkyq commented on lib/src/screens/ionia/cards/ionia_buy_gift_card.dart
> +  String get title => 'Enter Amount';
Please add to localization file

2022-06-13 17:49 UTC, godilite commented on lib/src/screens/dashboard/widgets/market_place_page.dart
> +  @override
done

2022-06-14 13:24 UTC, mkyq commented on lib/src/screens/ionia/cards/ionia_debit_card_page.dart
> +    final spendLimit = widget.isCardSample ? '10000' : widget.cardInfo.spendLimit.toStringAsFixed(2);
I would to move it into getters

2022-06-14 13:32 UTC, mkyq commented on lib/src/screens/ionia/cards/ionia_debit_card_page.dart
> +                      '${widget.cardInfo.expirationMonth ?? 'MM'}/${widget.cardInfo.expirationYear ?? 'YY'}',
Please move to localization file (MM and YY)

2022-06-14 13:46 UTC, mkyq commented on lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
> +          hintText: 'Search',
Please add to localization file

2022-06-15 11:25 UTC, mkyq approved these changes

2022-06-15 11:26 UTC, merged