Enable differenct currencies
cake-tech/cake_wallet pull request #394
Opened 2022-06-23 16:02 UTC by OmarHatem28

2022-06-23 16:07 UTC, OmarHatem28 commented
@mkyq I noticed that there is already a widget `Picker` that has some of the desired UI while looking into CW-104 and 106, anyway it would have needed some refactoring to allow the required change currency design.
However, I am refactoring `Picker` right now while working on the new design and the new `CurrencyAlertDialog` in this PR will be removed then.

2022-06-28 16:55 UTC, mkyq requested changes

2022-06-28 16:55 UTC, mkyq commented on lib/view_model/buy/buy_amount_view_model.dart
> +  FiatCurrency fiatCurrency = FiatCurrency.usd;
set value inside of constructor

2022-06-28 16:55 UTC, mkyq commented on lib/src/widgets/currency_alert_dialog.dart
> +                    "Change Currency",
Add to localization file

2022-06-28 16:55 UTC, mkyq commented on lib/src/widgets/currency_alert_dialog.dart
> +            color: Color(0xff010615).withOpacity(0.8),
Please move all unnamed colors into theme

2022-06-28 17:37 UTC, closed without merging