Cw 150 cake pay introduction card
cake-tech/cake_wallet pull request #486
Opened 2022-08-26 06:30 UTC by Serhii-Borodenko

add an introduction card about Cake Pay service, for XMR, BTC, LTC wallets

2022-08-26 16:34 UTC, mkyq requested changes

2022-08-26 16:34 UTC, mkyq commented on lib/view_model/dashboard/balance_view_model.dart
> +  bool isShowCard = true;
Please value in constructor

2022-08-26 16:34 UTC, mkyq commented on lib/view_model/dashboard/balance_view_model.dart
> +    final  box = Hive.box<WalletInfo>('WalletInfo');
Inject hive box with DI

2022-08-26 16:34 UTC, mkyq commented on lib/view_model/wallet_creation_vm.dart
> +  => walletCreationService.typeExists(type);
Add space to arrow function sybmols as it's in function above

2022-08-26 16:34 UTC, mkyq commented on lib/view_model/dashboard/balance_view_model.dart
> +    await box.put(value.key, currentWallet);
Actually here you can use `await save()` on walletInfo for update information

2022-08-29 08:54 UTC, Serhii-Borodenko commented
done

2022-08-29 08:55 UTC, Serhii-Borodenko commented
@mkyq

2022-08-30 18:02 UTC, mkyq approved these changes

2022-08-30 18:03 UTC, merged