Сake pay filter white screen bug
cake-tech/cake_wallet pull request #491
Opened 2022-08-30 14:31 UTC by Serhii-Borodenko

rework card list view model

2022-08-30 18:35 UTC, mkyq commented
@Serhii-Borodenko Please fix merge conflicts

2022-08-31 08:20 UTC, Serhii-Borodenko commented
done

2022-09-02 14:08 UTC, mkyq requested changes

2022-09-02 15:04 UTC, mkyq approved these changes

2022-09-02 15:04 UTC, merged