CW-161 partial redemption fix
cake-tech/cake_wallet pull request #660
Opened 2022-11-30 13:29 UTC by godilite

2022-12-12 19:49 UTC, SamsungGalaxyPlayer commented
@godilite can you rebase please? I'll test a newly build APK for this. Thanks!

2022-12-13 17:11 UTC, OmarHatem28 requested changes

2022-12-13 17:11 UTC, OmarHatem28 commented on lib/src/screens/ionia/cards/ionia_more_options_page.dart
> +          )),
**Minor:**
Fix format and remove un-necessary `,` from `SizedBox` so it can take only 1 line

2022-12-13 17:37 UTC, OmarHatem28 approved these changes

2022-12-13 17:37 UTC, merged