Add Turkish Language
cake-tech/cake_wallet pull request #724
Opened 2023-01-10 23:25 UTC by HardenedSteel

* Line between 584-588 translated as a single sentence then splitted back to 3 line otherwise the translation wouldn't be possible properly. So if these lines are used in different order or alone the user wouldn't understand.
* Line 623 and 624 are not possible to translate alone. I can try to find alternative solutions if you let me know how this lines are used.

Closes #702 
XMR address for bounty payout: `86cpEsund6BWc2rm3qviqv8fpY2sABNW6W2ZuVK3bEBq6jqwYwpJDdJhFkLw9aXvDr8Mu2rZcasNJfLRS1APdzEZ4CpPdDs`

2023-01-12 19:04 UTC, SamsungGalaxyPlayer commented
Flag should be 42x26 not 42x36, apologies! https://github.com/cake-tech/cake_wallet/pull/729

2023-01-13 15:15 UTC, SamsungGalaxyPlayer approved these changes

2023-01-19 14:21 UTC, OmarHatem28 requested changes

2023-01-19 14:21 UTC, OmarHatem28 commented on res/values/strings_tr.arb
> +  "add_fund_to_card": "Ön ödemeli kartlara para ekle (En fazla yüklenebilir tutar: ${değer})",
this is causing an error as you translated the parameter ${value} with a word that contains a non-ASCII character 'ğ', the parameters should NOT be translated.

2023-01-19 14:22 UTC, OmarHatem28 commented on res/values/strings_tr.arb
> +  "add_fund_to_card": "Ön ödemeli kartlara para ekle (En fazla yüklenebilir tutar: ${değer})",
also please add the language to the currently supported languages section in the ReadME [here](https://github.com/cake-tech/cake_wallet#current-list-of-language-files)

2023-01-20 13:35 UTC, OmarHatem28 approved these changes

2023-01-20 13:35 UTC, merged