[skip ci] add restoring wallet from qr
cake-tech/cake_wallet pull request #793
Opened 2023-02-20 15:57 UTC by Serhii-Borodenko

2023-04-17 15:50 UTC, OmarHatem28 requested changes

2023-04-17 15:50 UTC, OmarHatem28 commented on lib/view_model/wallet_new_vm.dart
can be reverted

2023-04-17 15:50 UTC, OmarHatem28 commented on lib/view_model/wallet_restoration_from_keys_vm.dart
can be reverted

2023-04-17 15:50 UTC, OmarHatem28 commented on lib/view_model/wallet_restoration_from_seed_vm.dart
can be reverted

2023-04-17 15:50 UTC, OmarHatem28 commented on lib/view_model/wallet_creation_vm.dart
> +  Future<WalletBase> process(WalletCredentials credentials, RestoredWallet? restoreWallet) =>
and then upon check on whether `restoreWallet` is null or not you can decide which function. to call
i.e
`restoreWallet != null ? getCredentialsFromRestoredWallet(credentials, brestoreWallet : getCredentials(credentials)`

names are examples, you can change it for a better one

2023-04-18 09:56 UTC, Serhii-Borodenko commented on lib/di.dart
> +        getIt.get<WalletCreationService>(param1: WalletType.monero),
Because the type of wallet is unknown before scanning the QR code

2023-04-18 10:21 UTC, Serhii-Borodenko commented on lib/router.dart
> +          builder: (_) => getIt.get<RestoreOptionsPage>(param1: isNewInstall));
`isNewInstall` should determine which workflow is used, fresh install or restore of a wallet from the settings menu

2023-04-18 10:42 UTC, Serhii-Borodenko commented on lib/router.dart
> +      return isNewInstall ? CupertinoPageRoute<void>(
Here should be pass isNewInstall argument, fixed.

2023-04-18 10:45 UTC, Serhii-Borodenko commented on lib/router.dart
> +              param2: false));
This is used in different workflows

2023-04-20 00:35 UTC, OmarHatem28 requested changes
Please find another way other than passing a hard-coded value at runtime then changing it

2023-04-20 00:35 UTC, OmarHatem28 commented on lib/di.dart
> +        getIt.get<WalletCreationService>(param1: WalletType.monero),
Nope, please don't do that, there are a lot of other ways to implement this,
either setting the wallet type for `WalletCreationService` as nullable or getting the instance from `getIt` when you get the wallet type from the scanned QR code thus passing the type, but not passing a hard-coded value that you will change later

2023-04-21 18:35 UTC, OmarHatem28 approved these changes

2023-04-21 18:36 UTC, merged