CW-331-Add-option-to-disable-market-place-in-display-settings
cake-tech/cake_wallet pull request #872
Opened 2023-04-10 17:52 UTC by Blazebrain

Issue Number (if Applicable): Fixes #

# Description
Add switcher in display settings to enable/disable marketplace page

if enabled: it will be the same behavior as it is right now

if disabled: the dashboard screen will only have the balance and transactions screen

# Pull Request - Checklist  

- [x] Initial Manual Tests Passed
- [] Double check modified code and verify it with the feature/task requirements
- [x] Formate code
- [x] Look for code duplication
- [x] Clear naming for variables and methods

2023-04-11 14:31 UTC, OmarHatem28 requested changes
also, you haven't added a reaction for `shouldShowMarketPlaceInDashboard` to save its new value in the shared prefs.
and please revert the formatting in `settings_store` and in `dashboard_page`

2023-04-12 09:28 UTC, Blazebrain commented on lib/store/settings_store.dart
> +        false;
Fixed this  @OmarHatem28

2023-04-12 09:29 UTC, Blazebrain commented
> also, you haven't added a reaction for `shouldShowMarketPlaceInDashboard` to save its new value in the shared prefs to be persistent.
> and please revert the formatting in `settings_store` and in `dashboard_page`

Added the persistence also, and remove trailing commas format I added in the store and dashboard

2023-04-13 04:21 UTC, OmarHatem28 commented
Reviewed ok, please check Justin's comment on Jira

2023-04-13 14:04 UTC, SamsungGalaxyPlayer commented
@OmarHatem28 tests ok now

2023-04-16 13:45 UTC, OmarHatem28 approved these changes

2023-04-16 13:45 UTC, merged