CW-351-Add-option-in-Privacy-settings-to-enable-disable-screenshots
cake-tech/cake_wallet pull request #885
Opened 2023-04-17 11:59 UTC by Serhii-Borodenko

Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Formate code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

2023-04-19 21:26 UTC, SamsungGalaxyPlayer commented
Resolves https://github.com/cake-tech/cake_wallet/pull/885 and https://github.com/cake-tech/cake_wallet/issues/340

2023-04-20 01:07 UTC, OmarHatem28 requested changes

2023-04-20 01:07 UTC, OmarHatem28 commented on res/values/strings_en.arb
add other translations as well please

2023-04-20 09:48 UTC, OmarHatem28 approved these changes

2023-04-20 10:00 UTC, merged