CW-427-Refactor-wallet-type-selection-UI
cake-tech/cake_wallet pull request #968
Opened 2023-06-14 12:45 UTC by Serhii-Borodenko

Issue Number (if Applicable): Fixes #

# Description

refactored the asset selection screen

# Pull Request - Checklist  

- [x] Initial Manual Tests Passed
- [x] Double check modified code and verify it with the feature/task requirements
- [x] Format code
- [x] Look for code duplication
- [x] Clear naming for variables and methods

2023-07-08 02:06 UTC, OmarHatem28 requested changes

2023-07-08 02:06 UTC, OmarHatem28 commented on lib/src/screens/new_wallet/new_wallet_type_page.dart
> +      filteredTypes = types;
**Minor:**
unnecessary assigning

2023-07-09 09:17 UTC, Serhii-Borodenko commented on lib/src/screens/new_wallet/new_wallet_type_page.dart
> +      filteredTypes = types;
done

2023-07-10 15:12 UTC, OmarHatem28 approved these changes

2023-07-10 15:12 UTC, merged